project_name: nomad
run_name: vanilla_nomad

# training setup
use_wandb: True # set to false if you don't want to log to wandb
train: True
batch_size: 200
eval_batch_size: 200
epochs: 50
gpu_ids: [0]
num_workers: 4
lr: 1e-4
optimizer: adamw
clipping: False
max_norm: 1.
scheduler: "cosine"
warmup: True 
warmup_epochs: 4
cyclic_period: 10
plateau_patience: 3
plateau_factor: 0.5
seed: 0

# model params
model_type: nomad
vision_encoder: nomad_vint
encoding_size: 256
obs_encoder: efficientnet-b0
attn_unet: False
cond_predict_scale: False
mha_num_attention_heads: 4
mha_num_attention_layers: 4
mha_ff_dim_factor: 4
down_dims: [64, 128, 256]

# diffusion model params
num_diffusion_iters: 10

# mask 
goal_mask_prob: 0.5

# normalization for the action space
normalize: False

# context
context_type: temporal
context_size: 3 # 5
alpha: 1e-4

# distance bounds for distance and action and distance predictions 
distance:
  min_dist_cat: 0
  max_dist_cat: 20
action:
  min_dist_cat: 3
  max_dist_cat: 20

# action output params
len_traj_pred: 8
learn_angle: False

# dataset specific parameters
image_size: [96, 96] # width, height
datasets:
  mars_rock:
    data_folder: /home/apatnaik/git/visualnav-transformer/datasets/sim_mars_rock
    train: /home/apatnaik/git/vanilla_nomad/train/vint_train/data/data_splits/mars_rock/train/
    test: /home/apatnaik/git/vanilla_nomad/train/vint_train/data/data_splits/mars_rock/test/
    end_slack: 0
    goals_per_obs: 1 # increase dataset size
    negative_mining: True
  # mars-rock:
  #   data_folder: /data/vlam/processed/mars-rock
  #   train: /home/jbecktor/git/visualnav-transformer/train/vint_train/data/data_splits/mars-rock/train/
  #   test: /home/jbecktor/git/visualnav-transformer/train/vint_train/data/data_splits/mars-rock/test/
  #   end_slack: 0
  #   goals_per_obs: 2 # increase dataset size
  #   negative_mining: True
  # marsbot_science_rock:
  #   data_folder: /data/vlam/processed/marsbot_science_rock
  #   train: /home/jbecktor/git/visualnav-transformer/train/vint_train/data/data_splits/marsbot_science_rock/train/
  #   test: /home/jbecktor/git/visualnav-transformer/train/vint_train/data/data_splits/marsbot_science_rock/test/
  #   end_slack: 0
  #   goals_per_obs: 2 # increase dataset size
  #   negative_mining: True
  # spot_garage:
  #   data_folder: /data/vlam/processed/spot_garage
  #   train: /home/apatnaik/git/visualnav-transformer/train/vint_train/data/data_splits/spot_garage/train/
  #   test: /home/apatnaik/git/visualnav-transformer/train/vint_train/data/data_splits/spot_garage/test/
  #   end_slack: 0
  #   goals_per_obs: 2 # increase dataset size
  #   negative_mining: True
  # mars_yard:
  #   data_folder: /data/vlam/processed/mars_yard
  #   train: /home/jbecktor/git/visualnav-transformer/train/vint_train/data/data_splits/mars_yard/train/
  #   test: /home/jbecktor/git/visualnav-transformer/train/vint_train/data/data_splits/mars_yard/test/
  #   end_slack: 0
  #   goals_per_obs: 3 # increase dataset size
  #   negative_mining: True
  # figure8_sky:
  #   data_folder: /data/vlam/processed/figure8_sky
  #   train: /home/jbecktor/git/visualnav-transformer/train/vint_train/data/data_splits/figure8_sky/train/
  #   test: /home/jbecktor/git/visualnav-transformer/train/vint_train/data/data_splits/figure8_sky/test/
  #   end_slack: 0
  #   goals_per_obs: 2 # increase dataset size
  #   negative_mining: False
  recon:
    data_folder: /home/apatnaik/git/visualnav-transformer/datasets/recon
    train: /home/apatnaik/git/vanilla_nomad/train/vint_train/data/data_splits/recon/train/ # path to train folder with traj_names.txt
    test: /home/apatnaik/git/vanilla_nomad/train/vint_train/data/data_splits/recon/test/ # path to test folder with traj_names.txt
    end_slack: 3 # because many trajectories end in collisions
    goals_per_obs: 1 # how many goals are sampled per observation
    negative_mining: True # negative mining from the ViNG paper (Shah et al.)
  go_stanford:
    data_folder: /data/vlam/processed/go_stanford # datasets/stanford_go_new
    train: /home/apatnaik/git/vanilla_nomad/train/vint_train/data/data_splits/go_stanford/train/
    test: /home/apatnaik/git/vanilla_nomad/train/vint_train/data/data_splits/go_stanford/test/
    end_slack: 0
    goals_per_obs: 2 # increase dataset size
    negative_mining: True
  # tartan_drive:
  #   data_folder: /home/<username>/nomad_dataset/tartan_drive/
  #   train: /home/<username>/data_splits/tartan_drive/train/
  #   test: /home/<username>/data_splits/tartan_drive/test/
  #   end_slack: 3 # because many trajectories end in collisions
  #   goals_per_obs: 1
  #   negative_mining: True
  sacson:
    data_folder: /home/apatnaik/git/visualnav-transformer/datasets/huron
    train: /home/apatnaik/git/vanilla_nomad/train/vint_train/data/data_splits/sacson/train/
    test: /home/apatnaik/git/vanilla_nomad/train/vint_train/data/data_splits/sacson/test/
    end_slack: 3 # because many trajectories end in collisions
    goals_per_obs: 1
    negative_mining: True
  scand:
    data_folder: /home/apatnaik/git/visualnav-transformer/datasets/scand
    train: /home/apatnaik/git/vanilla_nomad/train/vint_train/data/data_splits/scand/train/
    test: /home/apatnaik/git/vanilla_nomad/train/vint_train/data/data_splits/scand/test/
    end_slack: 0
    goals_per_obs: 1
    negative_mining: True
  mars_yard:
    data_folder: /home/apatnaik/git/visualnav-transformer/datasets/mars_yard
    train: /home/apatnaik/git/vanilla_nomad/train/vint_train/data/data_splits/mars_yard/train/
    test: /home/apatnaik/git/vanilla_nomad/train/vint_train/data/data_splits/mars_yard/test/
    end_slack: 0
    goals_per_obs: 3
    negative_mining: True
  spot4_mars_yard:
    data_folder: /home/apatnaik/git/visualnav-transformer/datasets/spot4_mars_yard
    train: /home/apatnaik/git/vanilla_nomad/train/vint_train/data/data_splits/spot4_mars_yard/train/
    test: /home/apatnaik/git/vanilla_nomad/train/vint_train/data/data_splits/spot4_mars_yard/test/
    end_slack: 0
    goals_per_obs: 3
    negative_mining: True
  spot4_garage:
    data_folder: /home/apatnaik/git/visualnav-transformer/datasets/spot4_garage
    train: /home/apatnaik/git/vanilla_nomad/train/vint_train/data/data_splits/spot4_garage/train/
    test: /home/apatnaik/git/vanilla_nomad/train/vint_train/data/data_splits/spot4_garage/test/
    end_slack: 0
    goals_per_obs: 3
    negative_mining: True

# logging stuff
## =0 turns off
print_log_freq: 100 # in iterations
image_log_freq: 1000 #0 # in iterations
num_images_log: 8 #0 
pairwise_test_freq: 0 # in epochs
eval_fraction: 0.25
wandb_log_freq: 5 # in iterations
eval_freq: 1 # in epochs